require:
  - "rubocop-rails"
  - "rubocop-rspec"

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/Rspec/InferredSpecType:
  Enabled: false

Layouts/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
