require: 'rubocop-rails'

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
