require:
  - "rubocop-rails"
  - "rubocop-rspec"
  - "rubocop-factory_bot"

inherit_gem:
  action_policy: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/Rails/InferredSpecType:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"
    - "db/migrate/*.rb"

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*.rb"
